version: 2
jobs:
  build:
    machine: true
    context: org-global
    steps:
      - checkout
      - run:
          docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          docker build -t nikolaylagutko/ci-java9-sbt
      - run:
          docker push
workflows:
  version: 2
  build:
    jobs:
      - biuld:
          context: org-global
